version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.9.1
  - dependency-name: pm2
    versions:
    - 4.5.5
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: systeminformation
    versions:
    - 4.33.5
    - 4.34.9
  - dependency-name: sass
    versions:
    - 1.32.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.9
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.9
  - dependency-name: sass-loader
    versions:
    - 10.1.0
  - dependency-name: vue-router
    versions:
    - 3.4.9
