integration:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/*.yml'
    - 'scripts/**'
    - 'test/**'

localization:
- changed-files:
  - any-glob-to-any-file:
    - 'locales/**'

experiences:
- changed-files:
  - any-glob-to-any-file:
    - 'src/components/**'
    - 'src/layouts/**'

publications:
- changed-files:
  - any-glob-to-any-file:
    - 'src/pages/**'

enhancement:
- changed-files:
  - any-glob-to-any-file: '**'
