language: ruby

rvm:
- 2.2.1

env:
  global:
    secure: eBWykPCIs69EvlkJP/Wnvs/A8l3y4+66t0OdkInSNySu1iExbfsCmyzBLr3IoWO2IJI5owTASJWoCXDuO6i7bf9FmAt86OiHH00AS4XlN6xLgJQRl0Ogitte/RkYruEEgkHvSAy7M0GcEdH9xZGmlfz1elk8YOV2GvL2onNI4v1KskhtBt+L9uBlkL72c1ehDbkNW6kL8BsPIVKeZHoYQHB6pBXTzKE34oZGMV4SrIJMcQjL9B+LxHp7paj28iD7dug7S2j2E6crCiPwm3Owsh+pMwizRDigQgjNOzZoa+M3H/1nlrsc9zLbs3vOPHOYpagoJIVvVOMk1M443kMqORnoaWZ8h/e/IiTbr+I/DCTVhQDsw3QuKQ/RJDsVZMMo0mbRO4qtKJehuxuYGdQHzv4gDlksNxCKYWiu0q1m2I3qsAkPXmGvwd4Pnt9lJtFHwUrZtDnCAN4fftZU2WN0eUL4jvRb6+O6Ik+IQS52DieyZOyw+yCAH8oofzLOcOludqMJuGq4/mdluL4jOaZCRbfXsu43bKq0owSsPDGV20uqH5Dj5vVjCkRgd3dK7P6f83VZwtfZEwBlD5IPYTTZIw7kjixNTPyqNtzYL7hlLzd0S/cYzNLqowTTlDqrTs3musGcNmjNbXktD3AcYoOHZNH7QvR7R/m4ZYjKhkvODck=

cache: bundler

matrix:
  fast_finish: true

before_install:
- gem update --system

before_script:
- rake install

script:
- rake deploy
