language: ruby

rvm:
  - 2.2.1

matrix:
  fast_finish: true

before_install:
  - gem update --system

install:
  - bundle install

before_script:
  - rake install

script:
  - rake build

after_script:
  - rake deploy
