language: ruby
rvm:
- 2.2.0
cache:
  bundler: true
  directories:
  - ".bundle"
matrix:
  fast_finish: true
before_install:
- gem update --system
install:
- bundle install
- rake install
script:
- rake deploy
env:
  global:
    secure: hiyVkqmjyNmr0DGXlYw1SI/UgmkRYcdtttHze8IRoZDhghyzsAdErySZV/rmSlc2/qSVTBl6ZjKWHTpKb57ziwAwx7GsnUgexsCuXnuiTTpURA4XlxVXgWUXZo48jilyeve3wF6hmT/jYxkKmjhznzP9OGOGQeQaSWChKyayJ2Asd51kNlnrT1DtF8qQryc6JZKHJccZ/WtmvBajwptdipz9h2UBeWNRmj4L8W7v1ohHi/uNQMTKFJ1Ujtk4ze+3yltGg3cyG32qbe21lR6foUsxi/qrgLmHIw76WLF19VoOmF52Q2joeBTQtA1QHMSfj9dgTpYQmcut/QXuJNdcQsqeyMZ5o57yjHK3/hkn8Q/lMj1szvQ1H60wIhgU4TOiwm99iZO3uZJkSOfxEsGEzbf917Mu+WPRhboxAVaEi1rS/3+qRbTSCLotGw5bQApy56GpqK+MJ1IQNwC5FfzAJTpDxKGIXgF5ida5Mn5OmNGjV65yEvmDkJ9iUEIDp87UFPQgcmRymTVgpCT1YWPywNAUINI1itNX/OV66p47u+PIx5h5l498/4fU2OqtcLxoKTiIKQT1+FHSWaAMFgmevRFpDDyAbbtJgh9odZL0jwK/b7ViCbV33S/tsMAI1EETXJDcStMUy0DWJ6uJm7tfIG1Pa/S57CqrC7iQ9/JeYU8=
