# Site settings
title:       Fery Wardiyanto's Blog
description: "Opensource enthusiast, Freelance web developer, Linux user and Coffee addict."
author:      Fery Wardiyanto
email:       hallo@feryardiant.me
# email:       ferywardiyanto@gmail.com
address:     'Somewhere in.<br>Pekalongan, Indonesia'
gravatar:    f1d26a5fe1c5ecc75c660c89ceb6d68e

# Server
baseurl:     '' # the subpath of your site, e.g. /posts/
url:         //feryardiant.me # the base hostname & protocol for your site
encoding:    UTF-8
timezone:    Asia/Jakarta

# Analytics and webmaster tools stuff goes here
google_analytics: UA-51394056-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Personal settings
show_portfolio: false
googleplus:     ferywardiyanto
twitter:        feryardiant
github:         feryardiant
linkedin:       feryardiant
dribbble:       feryardiant

# Disqus post comments
disqus_shortname: fa-octo

# Post sharing icons
show_sharing_icons:  true
share_text:          'Share this post!'
# Change to 'true' to enable individual icons
share_facebook:      true
share_twitter:       true
share_googleplus:    true
share_linkedin:      false
share_digg:          false
share_tumblr:        false
share_reddit:        false
share_stumbleupon:   false
share_hackernews:    false

# Build settings
git_remote:      https://github.com/feryardiant/feryardiant.github.io
git_branch:      master
source:          source
destination:     dist
markdown:        kramdown
highlighter:     pygments
permalink:       /posts/:year/:month/:title.html
paginate:        1
paginate_path:   /posts/page/:num

collections:
  works:
    source:    _works
    output:    true
    permalink: /works/:path.html

defaults:
- scope:
    path: _works
    type: works
  values:
    layout: works

# Plugins
# plugins:
#   - twitter_tag

gems:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-archives
  - jekyll-gist
  - autoprefixer-rails
  - jemoji

# emoji:
#   src: /asset

# http://ixti.net/jekyll-assets/
assets:
  debug: false
  dirname: asset
  baseurl: //d3q0106j08jqcn.cloudfront.net/
  # baseurl: /asset/
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - asset/_scripts
    - asset/_styles
    - asset/_images
  cachebust: hard
  cache: true

jekyll-archives:
  enabled: ['year', 'month', 'tags']
  layouts:
    tag:   archive/tags
    year:  archive/years
    month: archive/months
  permalinks:
    tag:   '/posts/tags/:name.html'
    year:  '/posts/:year/'
    month: '/posts/:year/:month/'
