name: GitHub Page

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - .github/workflows/deployment.yml
      - src/pages/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up pnpm
      uses: pnpm/action-setup@v2.2.1

    - name: Setup Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Generate pages
      env:
        BASE_URL: https://feryardiant.id/
        VITE_GTM_KEY: GTM-5G6FXJ7
      run: |
        yarn build
        cp .gitignore dist/

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'build: generate github pages'
        folder: 'dist'
