name: GitHub Page

on:
  pull_request:
    branches:
      - source
  push:
    branches:
      - source
    paths:
      - .github/workflows/deployment.yml
      - src/pages/*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get cache path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install Dependencies
      run: yarn

    - name: Generate pages
      env:
        BASE_URL: https://feryardiant.id/
        VITE_GTM_KEY: GTM-5G6FXJ7
      run: |
        yarn build
        cp .gitignore dist/

    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/source'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.PAT }}
        commit-message: 'build: generate github pages'
        branch: master
        folder: 'dist'
