name: GitHub Page

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - env:
        BASE_URL: 'https://feryardiant.id/'
      run: npm run build
    - name: Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/source'
      uses: JamesIves/github-pages-deploy-action@v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        COMMIT_MESSAGE: 'build: generate github pages'
        FOLDER: 'dist'
