name: GitHub Page

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run lint
    - name: Build and Deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/source'
      uses: JamesIves/github-pages-deploy-action@2.0.0
      env:
        VUE_APP_NAME: 'Personal Blog'
        VUE_APP_COLOR: '#409EFF'
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: 'dist'
        BUILD_SCRIPT: npm run build
